inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
   - my_test/**/*
   - examples/**/*

Metrics/LineLength:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
